### ISSUE TITLE
Dune 2 mod - Asset Browser crashes

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/d2#10]
Browsing some files with the Asset Browser makes OpenRA crash.
**Credit12.SHP**
**Credit13.SHP** 
**Credit14.SHP**
**Credit15.SHP** 
**STATIC.WSA**

exception.log file: https://gist.github.com/x-a-n-a-x/2a306bba956b8f11e76d155c161c2baa

I am using the latest version of bleed (https://github.com/OpenRA/OpenRA/commit/6f75ddc8238e83ba30cd2cb941cf703f16e24e20) and the latest version of OpenRA/D2 : https://github.com/OpenRA/d2/commit/2de831db49ea0f4a8e1c957bfcfe61a3c461f2ab

**Comment by Micr0Bit** [comment]
theres not always the same crash-log ... some files cause different logs after crashing ... we need to document all of them

**Comment by karcel** [comment]
I saw in my friends pc also that after installing OpenRA and copying cutscenes from gruntmods to OpenRA/Contonet/d2k/v2/Movies the game crashed on clicking view Briefing AND on Extra -> Asset Browser and trying to play selected Movie. The error log from asset browser fiel contained:

```
Error reading A_BR02_E.VQA:
Attempted to read past the end of the stream.
   at OpenRA.StreamExts.ReadBytes(Stream s, Byte[] buffer, Int32 offset, Int32 count)
   at OpenRA.StreamExts.ReadBytes(Stream s, Int32 count)
   at OpenRA.StreamExts.ReadASCII(Stream s, Int32 length)
   at OpenRA.Mods.Common.FileFormats.VqaReader..ctor(Stream stream)
   at OpenRA.Mods.Common.Widgets.VqaPlayerWidget.Load(String filename)
   at OpenRA.Mods.Common.Widgets.Logic.AssetBrowserLogic.LoadAsset(IReadOnlyPackage package, String filename)
```
