### ISSUE TITLE
Can not launch game 

### ISSUE THREAD

**Issue by ZhiZe-ZG** [OpenRA/d2#211]
All PAK file has been copied to 'Documents\OpenRA\Content\d2' (Windows 10)
```
OpenRA engine version release-20210321
d2 mod mod version release-20210321
Date: 2021-10-27 17:05:19Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentOutOfRangeException`: Non-negative number required.
Parameter name: count
   at OpenRA.StreamExts.ReadBytes(Stream s, Int32 count) in D:\Github\d2-master\engine\OpenRA.Game\StreamExts.cs:line 25
   at OpenRA.Mods.D2.SpriteLoaders.WsaLoader.WsaTile..ctor(Stream s, Size size, ISpriteFrame prev) in D:\Github\d2-master\OpenRA.Mods.D2\SpriteLoaders\WsaLoader.cs:line 42
   at OpenRA.Mods.D2.SpriteLoaders.WsaLoader.ParseFrames(Stream s, ISpriteFrame prev) in D:\Github\d2-master\OpenRA.Mods.D2\SpriteLoaders\WsaLoader.cs:line 100
   at OpenRA.Mods.D2.SpriteLoaders.WsaLoader.TryParseSpriteWithPrevFrame(Stream s, ISpriteFrame prev, ISpriteFrame[]& frames, TypeDictionary& metadata) in D:\Github\d2-master\OpenRA.Mods.D2\SpriteLoaders\WsaLoader.cs:line 116
   at OpenRA.Mods.D2.SpriteLoaders.WsaLoader.TryParseSprite(Stream s, ISpriteFrame[]& frames, TypeDictionary& metadata) in D:\Github\d2-master\OpenRA.Mods.D2\SpriteLoaders\WsaLoader.cs:line 122
   at OpenRA.Graphics.FrameLoader.GetFrames(Stream stream, ISpriteLoader[] loaders, TypeDictionary& metadata) in D:\Github\d2-master\engine\OpenRA.Game\Graphics\SpriteLoader.cs:line 167
   at OpenRA.Graphics.FrameLoader.GetFrames(IReadOnlyFileSystem fileSystem, String filename, ISpriteLoader[] loaders, TypeDictionary& metadata) in D:\Github\d2-master\engine\OpenRA.Game\Graphics\SpriteLoader.cs:line 155
   at OpenRA.Graphics.FrameCache.<>c__DisplayClass1_0.<.ctor>b__0(String filename) in D:\Github\d2-master\engine\OpenRA.Game\Graphics\SpriteLoader.cs:line 142
   at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn) in D:\Github\d2-master\engine\OpenRA.Game\Exts.cs:line 136
   at OpenRA.Graphics.CursorSequence..ctor(FrameCache cache, String name, String cursorSrc, String palette, MiniYaml info) in D:\Github\d2-master\engine\OpenRA.Game\Graphics\CursorSequence.cs:line 34
   at OpenRA.Graphics.CursorProvider..ctor(ModData modData) in D:\Github\d2-master\engine\OpenRA.Game\Graphics\CursorProvider.cs:line 48
   at OpenRA.ModData.InitializeLoaders(IReadOnlyFileSystem fileSystem) in D:\Github\d2-master\engine\OpenRA.Game\ModData.cs:line 136
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in D:\Github\d2-master\engine\OpenRA.Game\Game.cs:line 449
   at OpenRA.Game.Initialize(Arguments args) in D:\Github\d2-master\engine\OpenRA.Game\Game.cs:line 402
   at OpenRA.Game.InitializeAndRun(String[] args) in D:\Github\d2-master\engine\OpenRA.Game\Game.cs:line 273
   at OpenRA.Launcher.Program.Main(String[] args) in D:\Github\d2-master\engine\OpenRA.Launcher\Program.cs:line 26
```

**Comment by evgeniysergeev** [comment]
Can reproduce only this:
```
launch-game.cmd                                                                                                                                                                                      Platform is Windows                                                                                                                                                                                                Engine version is release-20210321                                                                                                                                                                                 Using SDL 2 with OpenGL (ANGLE) renderer                                                                                                                                                                           Desktop resolution: 1920x1200                                                                                                                                                                                      Using resolution: 1024x768                                                                                                                                                                                         Using window scale 1,00                                                                                                                                                                                            OpenGL renderer: ANGLE (Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0)                                                                                                                                        OpenGL version: OpenGL ES 3.0.0 (ANGLE 2.1.0.ea8043b73f93)                                                                                                                                                         Using default sound device                                                                                                                                                                                         Internal mods:                                                                                                                                                                                                             d2: d2 mod (release-20210321)                                                                                                                                                                                      all: All mods (release-20210321)                                                                                                                                                                                   cnc: Tiberian Dawn (release-20210321)                                                                                                                                                                              d2k: Dune 2000 (release-20210321)                                                                                                                                                                                  modcontent: Mod Content Manager (release-20210321)                                                                                                                                                                 ra: Red Alert (release-20210321)                                                                                                                                                                                   ts: Tiberian Sun (release-20210321)                                                                                                                                                                        External mods:                                                                                                                                                                                                             cnc-release-20210321: Tiberian Dawn (release-20210321)                                                                                                                                                             d2k-release-20210321: Dune 2000 (release-20210321)                                                                                                                                                                 ra-release-20210321: Red Alert (release-20210321)                                                                                                                                                                  d2-release-20210321: d2 mod (release-20210321)                                                                                                                                                                     d2k-{DEV_VERSION}: Dune 2000 ({DEV_VERSION})                                                                                                                                                               Loading mod: d2                                                                                                                                                                                                    Exception of type `System.IO.FileNotFoundException`: File not found: IBM.PAL                                                                                                                                          at OpenRA.FileSystem.FileSystem.Open(String filename) in D:\gamedev\d2\engine\OpenRA.Game\FileSystem\FileSystem.cs:line 208                                                                                        at OpenRA.Mods.D2.D2LoadScreen.Init(ModData modData, Dictionary`2 info) in D:\gamedev\d2\OpenRA.Mods.D2\LoadScreens\D2LoadScreen.cs:line 93                                                                        at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen) in D:\gamedev\d2\engine\OpenRA.Game\ModData.cs:line 65                                                                            at OpenRA.Game.InitializeMod(String mod, Arguments args) in D:\gamedev\d2\engine\OpenRA.Game\Game.cs:line 438                                                                                                      at OpenRA.Game.Initialize(Arguments args) in D:\gamedev\d2\engine\OpenRA.Game\Game.cs:line 401                                                                                                                     at OpenRA.Game.InitializeAndRun(String[] args) in D:\gamedev\d2\engine\OpenRA.Game\Game.cs:line 270                                                                                                                at OpenRA.Launcher.Program.Main(String[] args) in D:\gamedev\d2\engine\OpenRA.Launcher\Program.cs:line 30                                                                                                                                                                                                                                                                                                                          ----------------------------------------                                                                                                                                                                           OpenRA has encountered a fatal error.          
```

If content is copied to `Documents\OpenRA\Content\d2`. Looks like after changes in engine, need to copy d2 contents at this path: `%USERPROFILE%\AppData\Roaming\OpenRA\Content\d2`

**Comment by evgeniysergeev** [comment]
Done in #213
