### ISSUE TITLE
do not run

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/d2#25]
First time then it starts in playtest:
![image](https://cloud.githubusercontent.com/assets/11130958/19028422/97a34236-895d-11e6-8cac-068e904c1f45.png)

in another time then it starts in playtest or everytime in dev:
Date: 2016-10-03 05:47:56Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Reflection.ReflectionTypeLoadException`: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OpenRA.Exts.GetNamespaces(Assembly a) in d:\Games\OpenRA-bleed\OpenRA.Game\Exts.cs:line 52
   at OpenRA.ObjectCreator.<.ctor>b__6(Assembly asm) in d:\Games\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 71
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenRA.ObjectCreator..ctor(Manifest manifest, FileSystem modFiles) in d:\Games\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 71
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen) in d:\Games\OpenRA-bleed\OpenRA.Game\ModData.cs:line 58
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 373
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass2f.<LoadMod>b__2d()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime) in d:\Games\OpenRA-bleed\OpenRA.Game\Primitives\ActionQueue.cs:line 53
   at OpenRA.Game.LogicTick() in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 577
   at OpenRA.Game.Loop() in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 712
   at OpenRA.Game.Run() in d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:line 752
   at OpenRA.Program.Run(String[] args) in d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 134
   at OpenRA.Program.Main(String[] args) in d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 41

**Comment by evgeniysergeev** [comment]
try to use this packed oramod https://github.com/OpenRA/d2/releases/download/20161019/d2.oramod with installed release-20161019.

**Comment by yaaaaa** [comment]
Thanks, it works!
AI now can duild a concrete walls =) cool
How can I compile or create archive (d2.oramod) of this mod from these repository myself?
